version: "3"
services:
  test-react-app:
    image: test-react-app:latest   
    container_name: test-react-app
    build: 
      context: .
    ports: 
      - "3000:3000"
    volumes:
      - "./logs/nginx:/var/log/nginx"